- name: Delete AWS Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: us-east-1
    sg_name: ecom-sg
  tasks:
    - name: Gather VPC info by name
      amazon.aws.ec2_vpc_net_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "ecom-vpc"
      register: vpc_info

    - name: Set VPC ID
      set_fact:
        vpc_id: "{{ vpc_info.vpcs[0].id }}"
      when: vpc_info.vpcs | length > 0

    - name: Gather Subnet info
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
      register: subnet_info
      when: vpc_id is defined

    - name: Terminate EC2 instances
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        state: absent
        filters:
          "tag:Environment": "Testing"

    - name: Delete Security Group
      amazon.aws.ec2_security_group:
        name: "{{ sg_name }}"
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        state: absent
      when: vpc_id is defined

    - name: Delete Subnets
      amazon.aws.ec2_vpc_subnet:
        region: "{{ region }}"
        subnet_id: "{{ item.id }}"
        state: absent
      loop: "{{ subnet_info.subnets }}"
      when: subnet_info.subnets is defined

    - name: Detach and Delete Internet Gateway
      amazon.aws.ec2_vpc_igw:
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        state: absent
      when: vpc_id is defined

    - name: Delete Route Tables
      amazon.aws.ec2_vpc_route_table_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
      register: rt_info
      when: vpc_id is defined

    - name: Delete route tables by ID
      amazon.aws.ec2_vpc_route_table:
        region: "{{ region }}"
        route_table_id: "{{ item.id }}"
        state: absent
      loop: "{{ rt_info.route_tables }}"
      when: rt_info.route_tables is defined

    - name: Delete the VPC
      amazon.aws.ec2_vpc_net:
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        state: absent
      when: vpc_id is defined
