kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: sri-role-binding
  namespace: robot-shop 
subjects:
- kind: User 
  name: sri 
  apiGroup: rbac.authorization.k8s.io 
roleRef:
  kind: Role
  name: sri-role 
  apiGroup: rbac.authorization.k8s.io
