kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: robot-shop
  name: sri-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "update", "delete"]
